In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [7]:
x, y = make_classification(n_samples=1000, n_features=10, n_informative=3,  n_classes=3, random_state=42)

In [8]:
x

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]])

In [9]:
y

array([1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1,
       2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1,
       2, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1,

In [10]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.30)

In [11]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(multi_class='ovr')
model.fit(xtrain, ytrain)
ypred = model.predict(xtest)

d:\ml codes\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [12]:
ypred

array([0, 0, 1, 0, 1, 2, 0, 2, 2, 1, 1, 1, 0, 0, 0, 0, 2, 1, 1, 1, 0, 2,
       1, 0, 0, 2, 1, 0, 0, 0, 0, 2, 0, 1, 0, 2, 2, 2, 2, 2, 1, 2, 2, 0,
       2, 2, 1, 1, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 1, 1, 0, 2, 0, 2, 2,
       0, 0, 0, 1, 1, 2, 2, 0, 1, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 1,
       2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 2, 1, 2, 0, 1, 2,
       2, 0, 0, 1, 1, 1, 2, 0, 1, 2, 0, 0, 2, 2, 1, 0, 2, 0, 1, 2, 2, 1,
       0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 1, 1, 0, 0, 2, 2, 2, 2, 1, 0, 2, 2,
       2, 2, 2, 0, 0, 1, 2, 1, 2, 0, 0, 1, 2, 0, 1, 2, 1, 2, 0, 1, 0, 2,
       0, 0, 1, 1, 1, 0, 2, 2, 2, 1, 2, 2, 0, 1, 0, 0, 1, 0, 0, 2, 2, 2,
       2, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 0, 0, 2, 0, 1, 1, 2, 2, 0, 1, 1,
       2, 0, 0, 1, 1, 2, 1, 0, 0, 2, 2, 2, 1, 2, 0, 2, 2, 0, 1, 1, 2, 2,
       0, 0, 2, 0, 2, 0, 1, 1, 0, 0, 1, 0, 1, 1, 2, 0, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 2, 1, 0, 2, 2, 0, 1, 2, 0,
       0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 1, 0, 0])